
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

  test_project:
    needs: build_project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn test

  docker_build_and_push:
    needs: test_project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn package

      - name: Build and Push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: rodrigosv231/gui-video1
          tags: latest
          registry: docker.io
          #          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#  docker_build_and_push2:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build with Maven
#        run: mvn package
#
#      - name: Login to Docker Hub
#        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Build and Push docker image
#        run: |
#          docker build -t rodrigosv231/gui-video1 .
#          docker push rodrigosv231/gui-video1:latest

  docker_build_and_push3:
    needs: test_project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn package

      - name: Build and Push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/rodrigosv231/gui-video1:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}